# Define a list of sticker IDs
sticker_ids = [
    "CAACAgIAAxkBAAJ9nmS4PZw0mMONTT09ES3bTqkf5jELAALiBQACP5XMCnNlX6_emGTgLwQ",
    "CAACAgIAAxkBAAJ9c2S4O6cs9pH8KN7yhrDl7640xlcgAAIUBwACRvusBO7y0rmZcxR1LwQ",
    "CAACAgIAAxkBAAJ9dGS4O8sBCb3pcCdJvyahBA4_HJsZAAJZDgADLiFLVN-fb7SfsrwvBA",
    "CAACAgEAAxkBAAJ9dWS4O_IxnK7nMk9Ceq90E-PREv-IAALrAQACOA6CEbOGBM7hnEk5LwQ",
    "CAACAgIAAxkBAAJ9dmS4PB75fyCW_dvPGXUWpnCbSKfiAAJGAANSiZEj-P7l5ArVCh0vBA",
    "CAACAgUAAxkBAAJ9d2S4PD0lrqkRasfwS6-HWLTAgEF-AALEAgACBG2gVsF1Ng9n9CrHLwQ",
    "CAACAgIAAxkBAAJ9eGS4PHXzaXTvfOC1Cj5jrwruPr2WAAIsAQAC9wLID6abwCn6K4ldLwQ",
    "CAACAgIAAxkBAAJ9emS4PKd04AO7szmXcfv8CysxsJLAAAIoAQACUomRIxpSPL-bbi9uLwQ",
    "CAACAgIAAxkBAAJ9nmS4PZw0mMONTT09ES3bTqkf5jELAALiBQACP5XMCnNlX6_emGTgLwQ",
    "CAACAgIAAxkBAAKeomS7lUciGWGOgIyOVYB1MWiwNQknAALuFAAC41VQSThLiq0CE2G8LwQ",
    "CAACAgIAAxkBAAKepWS7le-C9MRT5hcxpmcFtk8PNICuAAI_FgACzP64SpLMhLQUJjbpLwQ",
]

not_found_stickers = [
    "CAACAgIAAxkBAAKeo2S7laTyntXOsPsqOxKztakS9cL2AAJiFQACfZpQSbTG3o8XjtAyLwQ",
    "CAACAgIAAxkBAAKepGS7lcvlNdFWU4OW1AFKPVfdWAGPAAKgFwAC37QgSSCArCK7IMbJLwQ",
    "CAACAgIAAxkBAAKermS7lopXgaM-oW3rfDLVz5MLDlCuAALnCgACTQ8ISfqT241rZLjtLwQ",
    "CAACAgIAAxkBAAKer2S7lqTB7RRDAAEc17SKstv2uLk_mgAC5xMAAoQ4cElqKsK5hR_0gC8E",
    "CAACAgIAAxkBAAKesmS7lswysMiop1T02QJXzxBPvxt6AAJ4FQAC10xwSZU-kJWavP47LwQ",
    "CAACAgIAAxkBAAKes2S7lvzwI3ZYgi3gSjMRTEm0PgfJAAKDGAACXuk4SVhqIE0ojg7uLwQ",
]

hello_stickers = [
    "CAACAgIAAxkBAAKepmS7ljuaEfYSY9WSTnxNXxtcUeIwAAKsEwACOJ4hS9HIZVrp3vjbLwQ",
    "CAACAgIAAxkBAAKep2S7ljsY8LRXFoJoLhGrkkx57_sKAALlDAACqFTBSPxg3fTAdQLKLwQ",
]


photos = [
    "user.jpg",
    "user1.jpg",
    "user3.jpg",
    "user4.jpg",
    "user5.jpg",
    "user6.jpg"
]
